### ISSUE TITLE
Memory leak ?

### ISSUE THREAD

**Issue by m4nuC** [wevm/hono-og#27]
When running an application that generate a lot of image, the memory seem to be steadily increasing, after some point this error show up.

Can there be a memory leak somewhere ?

```
function getImports() {

 const imports = {};

 imports.wbg = {};

imports.wbg.__wbg_new_15d3966e9981a196 = function (arg0, arg1) {

  const ret = new Error(getStringFromWasm0(arg0, arg1));

^

error: SVG data parsing failed cause unknown token at 1:1

at /app/node_modules/@wevm/vercel-og/dist/index.node.js:26285:17

at WASM  ([wasm code])

at WASM  ([wasm code])

at new Resvg (/app/node_modules/@wevm/vercel-og/dist/index.node.js:26154:7)

at new Resvg2 (/app/node_modules/@wevm/vercel-og/dist/index.node.js:26396:5)

at /app/node_modules/@wevm/vercel-og/dist/index.node.js:26646:19
```

**Comment by jxom** [comment]
Using Bun? Could be Bun related but will need to investigate.

**Comment by m4nuC** [comment]
Yes it was using bun. Reproduction is pretty simple. 
- Send a bunch of POST queries on an /image route that includes an emoji
- Memory steadily goes up till eventually that error show up
- Removing the emoji fixes the issue

**Comment by m4nuC** [comment]
This also happens in nodejs.
Can't use this on any amount of traffic right now. Memory eventually grows up to 4gig then app breaks

**Comment by jxom** [comment]
Not sure if this is an issue with hono-og then, but maybe `@vercel/og`.

**Comment by m4nuC** [comment]
Could be, in which case this is bad. 

Seems strange though, I assume that package got exposed to quite some load

**Comment by jxom** [comment]
That’s only for the Bun output, Bun couldn’t handle loading external WASM files, so had to inline them.

**Comment by m4nuC** [comment]
@jxom so good new is that it doesn't look to be `@vercel/og`. I've tried to render image from a route using Satori directly and I can confirm that the memory does get garbage collected, so the leak is somewhere in `hono-og`

**Comment by jxom** [comment]
Didn’t you say it happens on Node.js though? Node.js uses the `@vercel/og` entry.

**Comment by m4nuC** [comment]
Satori + Resvg works fine on both node and bun

**Comment by jxom** [comment]
Not sure where the memory leak would arise then as this library is a simple wrapper over `@vercel/og` with basic Hono JSX -> React JSX conversion.

As always, a minimal reproducible example would help a lot so I can investigate further.

**Comment by m4nuC** [comment]
To reproduce.

Spin up a new app. I've tried Node and Bun.

Take any image path, eg: http://localhost:3000/image?image=.....

Add a memory logger middleware

```
  app.use("*", async (c, next) => {
    console.log(process.memoryUsage().external)
    await next();
  })
```

Run an https://www.artillery.io load test on that path

Notice the memory grows linearly with the number of calls and never gets garbage collected

**Comment by jxom** [comment]
Fixed via #28.
